In [2]:
!pip install texthero -U

  Attempting uninstall: Cython
    Found existing installation: Cython 0.29.15
    Uninstalling Cython-0.29.15:
      Successfully uninstalled Cython-0.29.15


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sparse-dot-topn 0.2.9 requires cython>=0.29.15, but you have cython 0.29.14 which is incompatible.
You should consider upgrading via the 'c:\users\sanchit\anaconda3\python.exe -m pip install --upgrade pip' command.


In [28]:
import pandas as pd
text_data = pd.read_csv('D:/Sem 8/END SEM PROJECT/clean_data.csv')
text_data

Marker                                              posts  \
0           Normal         Russia s Nuclear Threat Is More Than Words   
1       depression  watching some of the 90s and older tv shows/ca...   
2       depression  Cleaned the basement It was a pretty big deal ...   
3           Normal   Drug Cartels to Mexican Police:  Join Us or Die    
4           Normal  Liquor market remains buoyant amid US recessio...   
...            ...                                                ...   
166530      Normal  As buzz for "Hustlers" grows, the battle for t...   
166531  depression  Why can't I just die already... Tired of life,...   
166532      Normal                  Pakistan lifts the ban on YouTube   
166533  depression  How to over come So I have suffered from bad A...   
166534  depression  I have a solid mental block against medication...   

                                               clean_data  
0                             russia nuclear threat words  
1       watching 90s older tv shows cartoon makes feel...  
2       cleaned basement pretty big deal putting month...  
3                 drug cartels mexican police join us die  
4       liquor market remains buoyant amid us recessio...  
...                                                   ...  
166530  buzz hustlers grows battle top spot domestic b...  
166531  die already tired life way much explain wish d...  
166532                         pakistan lifts ban youtube  
166533  come suffered bad allergies chronic rhinitis '...  
166534  solid mental block medication depression thera...  

[166535 rows x 3 columns]

In [8]:
import texthero as hero
text_data['clean_data'] = hero.clean(text_data['posts'])


In [9]:
text_data['clean_data'] 

0                               russia nuclear threat words
1         watching 90s older tv shows cartoon makes feel...
2         cleaned basement pretty big deal putting month...
3                   drug cartels mexican police join us die
4         liquor market remains buoyant amid us recessio...
                                ...                        
166530    buzz hustlers grows battle top spot domestic b...
166531    die already tired life way much explain wish d...
166532                           pakistan lifts ban youtube
166533    come suffered bad allergies chronic rhinitis '...
166534    solid mental block medication depression thera...
Name: clean_data, Length: 166535, dtype: object

In [13]:
sent = text_data['clean_data'].tolist()
type(sent)

list

In [10]:
from pathlib import Path  
filepath = Path('D:/Sem 8/END SEM PROJECT/clean_data.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
text_data.to_csv(filepath,index=False) 

In [5]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

#Our sentences we like to encode
# sentences = ['This framework generates embeddings for each input sentence',
#     'Sentences are passed as a list of string.',
#     'The quick brown fox jumps over the lazy dog.']

sentences = text_data['clean_data'].tolist() 

#Sentences are encoded by calling model.encode()
embeddings = model.encode(sentences)

#Print the embeddings
# for sentence, embedding in zip(sentences, embeddings):
#     print("Sentence:", sentence)
#     print("Embedding:", embedding)
#     print("")

In [11]:
embeddings.shape

(166535, 384)

In [12]:
import numpy as np
np.savez('embeddings.npz', embeddings)
# embeddings = np.load('embeddings.npz')

In [13]:
import os
os.getcwd()

'D:\\Sem 6\\data'

In [64]:
from sklearn.decomposition import PCA
pca_model = PCA(n_components=100)
pca_model.fit(embedds)
print("Sum of variance ratios: ",sum(pca_model.explained_variance_ratio_))

Sum of variance ratios:  0.8343722804162809


In [29]:
y = np.asarray(text_data['Marker'])
label_map = {cat:index for index,cat in enumerate(np.unique(y))}
y_prep = np.asarray([label_map[l] for l in y])

label_map

{'Normal': 0, 'depression': 1}

In [35]:
x_comps = pca_model.transform(embedds)
x_comps.shape

(166535, 100)

In [1]:
import pandas as pd
df_text = pd.read_csv('D:/Sem 8/END SEM PROJECT/clean_data_text.csv')
df_text

Marker                                         clean_data
0           Normal                        russia nuclear threat words
1       depression  watching 90s older tv shows cartoon makes feel...
2       depression  cleaned basement pretty big deal putting month...
3           Normal            drug cartels mexican police join us die
4           Normal  liquor market remains buoyant amid us recessio...
...            ...                                                ...
166530      Normal  buzz hustlers grows battle top spot domestic b...
166531  depression  die already tired life way much explain wish d...
166532      Normal                         pakistan lifts ban youtube
166533  depression  come suffered bad allergies chronic rhinitis '...
166534  depression  solid mental block medication depression thera...

[166535 rows x 2 columns]

In [4]:
import numpy as np
embeddings = np.load('embeddings.npz')

In [13]:
embeddings.files

['arr_0']

In [32]:
embedds=embeddings['arr_0']

In [59]:
single = x_comps[166533]

In [60]:
single.reshape(1,-1)

array([[-0.651129  , -0.11504638, -0.46947262,  0.07619137, -0.52501535,
        -0.07911602,  0.12837148, -0.20439208,  0.05443027,  0.551519  ,
        -0.19587204,  0.16509515,  0.31057703, -1.0120077 , -0.22210765,
         0.46117073,  0.4543437 ,  0.22288089,  0.04500074,  0.1374414 ,
        -0.2940935 , -0.35381106,  0.30556428, -0.29716063, -0.19989936,
         0.14398968, -0.70666885, -1.0983615 ,  0.09617344,  0.22082715,
         0.01268007, -0.21702012, -0.33349103, -0.5736356 ,  0.55041766,
        -0.33100224,  0.48129013,  0.38032004, -0.03948212,  0.3834722 ,
         0.4246366 , -0.22832407,  0.37083006,  0.06688575,  0.74142116,
         0.02980442, -0.20399298,  0.0649858 , -0.2986439 ,  0.12807715,
        -0.01186774, -0.39184105, -0.19594091, -0.44369552, -0.3859027 ,
         0.3785161 ,  0.00979452, -0.05600143,  0.11149953,  0.48802388,
         0.43237406,  0.29916987,  0.02545708, -0.34982434,  0.5679552 ,
         0.2556388 ,  0.36476433, -0.30816513,  0.2

In [21]:
type(embedds)

numpy.ndarray

In [36]:
import numpy as np
import pandas as pd
import gensim
import nltk
import re
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [38]:
y_prep

array([0, 1, 1, ..., 0, 1, 1])

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x_comps,y_prep,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(133228, 100)
(33307, 100)
(133228,)
(33307,)


In [41]:
import time
start = time.time() 

svm_classifier = SVC()
svm_classifier.fit(x_train,y_train)

end = time.time()
process = round(end-start,2)
print("Support Vector Machine Classifier has fitted, this process took {} seconds".format(process))

Support Vector Machine Classifier has fitted, this process took 207.08 seconds


In [42]:
svm_classifier.score(x_test,y_test)

0.9932446632839943

In [1]:
import numpy as np
embeddings = np.load('newembeddings.npz')

In [2]:
embedds=embeddings['arr_0']

In [3]:
embedds.shape

(192244, 384)

In [4]:
import pandas as pd
text_data = pd.read_csv('D:/Sem 8/END SEM PROJECT/mixed_data.csv',encoding = "ISO-8859-1")
text_data

Marker                                              Posts
0       depression  My birthday is tomorrow. Yes, I will be turnin...
1       depression  I’m so fucking lonely. I  know most of this ...
2       depression  I feel like I’m losing my friends Hi.....Iâ€...
3           Normal  this is smack ONE OF THE BEST TRANCE SONGS IN ...
4       depression  My boyfriend is controlling me even though he ...
...            ...                                                ...
192239  depression  Is there a problem that is objectively too sma...
192240      Normal      nah, a nice big bagel! Too early for burgers!
192241      Normal        oh oh found some clothes!! And i love em xD
192242      Normal                              it's an awesome movie
192243  depression  I just want to end it all I fucking hate my li...

[192244 rows x 2 columns]

In [5]:
y = np.asarray(text_data['Marker'])
label_map = {cat:index for index,cat in enumerate(np.unique(y))}
y_prep = np.asarray([label_map[l] for l in y])

label_map

{'Normal': 0, 'depression': 1}

In [6]:
import numpy as np
import pandas as pd
import gensim
import nltk
import re
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
x_train,x_test,y_train,y_test = train_test_split(embedds,y_prep,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(153795, 384)
(38449, 384)
(153795,)
(38449,)


In [14]:
import time
start = time.time() 

svm_classifier = SVC()
svm_classifier.fit(x_train,y_train)

end = time.time()
process = round(end-start,2)
print("Support Vector Machine Classifier has fitted, this process took {} seconds".format(process))

Support Vector Machine Classifier has fitted, this process took 2782.03 seconds


In [42]:
single = embedds[2].reshape(1,-1)

In [16]:
svm_classifier.score(x_test,y_test)

0.9876979895445915

In [53]:
import texthero as hero
sample = {'','I have always been encouraged to pursue what i like and its always made me feel content and happy','My family is very supportive but despite that i lack motivation and that makes me feel low. Sometimes i feel like i should end it all','i dont stress about it a lot','i was feeling low and listening to sad songs made me more depressed i started thinking that i am worth nothing','i am very happy about it'}

import pandas as pd
df = pd.DataFrame(sample, columns = ['sample'])
df['clean_data'] = hero.clean(df['sample'])
sample_sent = df['clean_data'].tolist() 

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')
samp_embeddings = model.encode(sample_sent)
df

sample  \
0  My family is very supportive but despite that ...   
1  I have always been encouraged to pursue what i...   
2                       i dont stress about it a lot   
3  i was feeling low and listening to sad songs m...   
4                           i am very happy about it   

                                          clean_data  
0  family supportive despite lack motivation make...  
1  always encouraged pursue like always made feel...  
2                                    dont stress lot  
3  feeling low listening sad songs made depressed...  
4                                              happy

In [55]:
svm_classifier.predict(samp_embeddings[2].reshape(1,-1))

array([0])

In [44]:
single = embedds[3].reshape(1,-1)
svm_classifier.predict(single.reshape(1,-1))

array([0])

In [56]:
from sklearn import model_selection

In [57]:
import pickle


In [58]:
# save the model to disk
filename = 'depression_model.sav'
pickle.dump(svm_classifier, open(filename, 'wb'))